In [1]:
import pandas as pd
import numpy as np
import os
pd.set_option('display.max_columns', None)
#pd.set_option('display.max_rows',None)
from datetime import datetime, timedelta

In [2]:
k=1
# Folder Path 
path = r"C:\Users\Ratan Kumar Jha\Desktop\welcome msg\WELCOME_MSG_OUTPUT"

os.chdir(path) 
dataframe = []

for file in os.listdir():
	if file.endswith('.csv'): 
		#file_path = f"{path}\{file}"
		file_path_name = os.path.join(path, file)
		print(file_path_name)
		read_csv_file = pd.read_csv(file_path_name)
		dataframe.append(read_csv_file)
FINAL_DATA_ALL_MERGE = pd.concat(dataframe, ignore_index=True)

C:\Users\Ratan Kumar Jha\Desktop\welcome msg\WELCOME_MSG_OUTPUT\concatenated_data_April.csv

C:\Users\Ratan Kumar Jha\AppData\Local\Temp\ipykernel_20404\1505414083.py:13: DtypeWarning: Columns (6,15,17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  read_csv_file = pd.read_csv(file_path_name)

C:\Users\Ratan Kumar Jha\Desktop\welcome msg\WELCOME_MSG_OUTPUT\concatenated_data_Aug.csv

C:\Users\Ratan Kumar Jha\AppData\Local\Temp\ipykernel_20404\1505414083.py:13: DtypeWarning: Columns (6,15,17,18,40) have mixed types. Specify dtype option on import or set low_memory=False.
  read_csv_file = pd.read_csv(file_path_name)

C:\Users\Ratan Kumar Jha\Desktop\welcome msg\WELCOME_MSG_OUTPUT\concatenated_data_FEB.csv
C:\Users\Ratan Kumar Jha\Desktop\welcome msg\WELCOME_MSG_OUTPUT\concatenated_data_jan.csv
C:\Users\Ratan Kumar Jha\Desktop\welcome msg\WELCOME_MSG_OUTPUT\concatenated_data_july.csv

C:\Users\Ratan Kumar Jha\AppData\Local\Temp\ipykernel_20404\1505414083.py:13: DtypeWarning: Columns (6,15,17,19,39) have mixed types. Specify dtype option on import or set low_memory=False.
  read_csv_file = pd.read_csv(file_path_name)

C:\Users\Ratan Kumar Jha\Desktop\welcome msg\WELCOME_MSG_OUTPUT\concatenated_data_june.csv

C:\Users\Ratan Kumar Jha\AppData\Local\Temp\ipykernel_20404\1505414083.py:13: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  read_csv_file = pd.read_csv(file_path_name)

C:\Users\Ratan Kumar Jha\Desktop\welcome msg\WELCOME_MSG_OUTPUT\concatenated_data_March.csv

C:\Users\Ratan Kumar Jha\AppData\Local\Temp\ipykernel_20404\1505414083.py:13: DtypeWarning: Columns (40) have mixed types. Specify dtype option on import or set low_memory=False.
  read_csv_file = pd.read_csv(file_path_name)

C:\Users\Ratan Kumar Jha\Desktop\welcome msg\WELCOME_MSG_OUTPUT\concatenated_data_May.csv

C:\Users\Ratan Kumar Jha\AppData\Local\Temp\ipykernel_20404\1505414083.py:13: DtypeWarning: Columns (3,6,15,17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  read_csv_file = pd.read_csv(file_path_name)

C:\Users\Ratan Kumar Jha\Desktop\welcome msg\WELCOME_MSG_OUTPUT\concatenated_data_Sep.csv

C:\Users\Ratan Kumar Jha\AppData\Local\Temp\ipykernel_20404\1505414083.py:13: DtypeWarning: Columns (40,41) have mixed types. Specify dtype option on import or set low_memory=False.
  read_csv_file = pd.read_csv(file_path_name)

In [3]:
FINAL_DATA_ALL_MERGE.shape

(2033394, 46)

In [4]:
#April_Data = pd.read_csv(r"C:\Users\Ratan Kumar Jha\Desktop\welcome msg\WELCOME_MSG_OUTPUT\concatenated_data_APRIL.csv")
#Jan_Data = pd.read_csv(r"C:\Users\Ratan Kumar Jha\Desktop\welcome msg\WELCOME_MSG_OUTPUT\concatenated_data_jan.csv")
#Feb_Data = pd.read_csv(r"C:\Users\Ratan Kumar Jha\Desktop\welcome msg\WELCOME_MSG_OUTPUT\concatenated_data_Feb.csv")
#March_Data = pd.read_csv(r"C:\Users\Ratan Kumar Jha\Desktop\welcome msg\WELCOME_MSG_OUTPUT\concatenated_data_March.csv")


# concat data

#JAN_FEB_DATA = pd.concat([Jan_Data, Feb_Data], ignore_index=True)
#JAN_FEB_MARCH_DATA = pd.concat([JAN_FEB_DATA, March_Data], ignore_index=True)
#FINAL_DATA_ALL_MERGE = pd.concat([JAN_FEB_MARCH_DATA, April_Data], ignore_index=True)

In [5]:
FINAL_DATA_ALL_MERGE['Category Name'].unique()

array(['NDS-IID(B)', 'DS-IID', 'LTIS-ID', 'IAS-IM', 'DS-II', 'NDS-IID(A)',
       'NDS-IID', 'DS2D', 'HGN', 'DS-llD', 'PUBWW', 'IAS1', 'LTIS1D',
       'NDS2D', 'DS1D', 'DS-iiD', 'LTEV', 'PWWD', 'NDS1D', 'IAS2D',
       'KJ_BPL_MTR', 'IAS-IIM', 'SS-I', 'NDS- IID(B)', 'KJ', 'LTS1D',
       'SS1D', 'LTIS-1D', nan, 'DS-IID(B)', 'LTIS-IID', 'DUMMY', 'NDS-ID'],
      dtype=object)

In [6]:
# Removing HGN and IAS1 data

FINAL_DATA_ALL_MERGE= FINAL_DATA_ALL_MERGE[(FINAL_DATA_ALL_MERGE['Category Name']!='HGN') & (FINAL_DATA_ALL_MERGE['Category Name']!='IAS1' )]

In [7]:
FINAL_DATA_ALL_MERGE.shape

(1502454, 46)

In [8]:
FINAL_DATA_ALL_MERGE['Category Name'].unique()

array(['NDS-IID(B)', 'DS-IID', 'LTIS-ID', 'IAS-IM', 'DS-II', 'NDS-IID(A)',
       'NDS-IID', 'DS2D', 'DS-llD', 'PUBWW', 'LTIS1D', 'NDS2D', 'DS1D',
       'DS-iiD', 'LTEV', 'PWWD', 'NDS1D', 'IAS2D', 'KJ_BPL_MTR',
       'IAS-IIM', 'SS-I', 'NDS- IID(B)', 'KJ', 'LTS1D', 'SS1D', 'LTIS-1D',
       nan, 'DS-IID(B)', 'LTIS-IID', 'DUMMY', 'NDS-ID'], dtype=object)

In [9]:
FINAL_DATA_ALL_MERGE.head(2)

,Section ID,WO Status,Work Order Type,Consumer ID,installation_number,New Meter No,S2S Meter,CA_NMI,Len,Duplicate,MDM_Status,Never,HES,NMI Status,mdm_AMR,mdm_master_data_sync,Meter Replacement,Communicating,mdm_Notification,Commissioning_Tag,Remarks,Detailed_Remarks,Mobile Number,Utility Name,Replacement Date,Aging,Bucket,Bucket1,Category Name,Type,Phase,Town,Origin_ID,Section_Name,Division_Name,Status,Vendor_Planner,Refurbished,Diff,2023-06-17 00:00:00,2024-06-17 00:00:00,fsdfaf,Refirbished,Check,Comments,Comment
0,CAFAB,edf_mi_verification_approved,Meter Replacement,100031180,5000129029,LT8071043,NaN,NaN,9,1,Installed,NaN,NaN,Y,Y,NaN,SUCCESS,NaN,NaN,Not Commissioned,Welcome Msg Not Sent,"NMI Success, AMR Not ""Y""",8.500010e+09,SBPD,2024-03-29,4,04 - 07,04 - 07,NDS-IID(B),Prepaid,3.0,Jahanabad,AI Engineering,Sec-Jahanabad(W),Jehanabad,Closed,AI_vp_jahn01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,CAFAB,edf_mi_verification_approved,Meter Replacement,100044522,5000142166,LT0726329,NaN,NaN,9,1,Installed,Never Communicating Meter,NaN,Y,Y,Y,SUCCESS,NaN,NaN,Not Commissioned,Welcome Msg Not Sent,Never Communicating Meter,9.905267e+09,SBPD,2022-11-13,506,>30,>180,DS-IID,Prepaid,1.0,Jahanabad,bhaskar_solar,Sec-Jahanabad(W),Jehanabad,Closed,bs_jahana_vp1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
FINAL_DATA_ALL_MERGE['Mobile Number'] = FINAL_DATA_ALL_MERGE['Mobile Number'].astype(str)


# Replacement date

FINAL_DATA_ALL_MERGE['Replacement Date'] = pd.to_datetime(FINAL_DATA_ALL_MERGE['Replacement Date'])

# DAYS ADDED



FINAL_DATA_ALL_MERGE['Aging_Creation_Date'] = FINAL_DATA_ALL_MERGE['Replacement Date'] + pd.to_timedelta(FINAL_DATA_ALL_MERGE['Aging'], unit='D')

FINAL_DATA_ALL_MERGE['Aging_Creation_Date_BACKDATE'] = FINAL_DATA_ALL_MERGE['Replacement Date'] - pd.to_timedelta(FINAL_DATA_ALL_MERGE['Aging'], unit='D')

In [11]:
# Final data all merge week wise data


FINAL_DATA_ALL_MERGE['Year-Week'] = FINAL_DATA_ALL_MERGE['Aging_Creation_Date'].dt.strftime('%Y-%U')
FINAL_DATA_ALL_MERGE['Week'] = FINAL_DATA_ALL_MERGE['Aging_Creation_Date'].dt.strftime('%U')
#FINAL_DATA_ALL_MERGE['Month'] = FINAL_DATA_ALL_MERGE['Aging_Creation_Date'].dt.strftime('%M')
FINAL_DATA_ALL_MERGE['Month'] = FINAL_DATA_ALL_MERGE['Aging_Creation_Date'].dt.month


FINAL_DATA_ALL_MERGE['Week'] = FINAL_DATA_ALL_MERGE['Week'].astype(int)

In [12]:
def add_one_in_Week(row):
    return row['Week'] + 1

FINAL_DATA_ALL_MERGE["Week"] =  FINAL_DATA_ALL_MERGE.apply(add_one_in_Week, axis=1)

In [13]:
def fun_Agging_bucket_30(row):
    if row['Aging'] < 31:
        return "<=30"
    else:
        return ">30"
    
FINAL_DATA_ALL_MERGE["Agging_bucket_30"] =  FINAL_DATA_ALL_MERGE.apply(fun_Agging_bucket_30, axis=1)

In [14]:
FINAL_DATA_ALL_MERGE['Resolved Cases'] = 0
FINAL_DATA_ALL_MERGE['Count'] = 1

In [15]:
FINAL_DATA_ALL_MERGE.head(2)

,Section ID,WO Status,Work Order Type,Consumer ID,installation_number,New Meter No,S2S Meter,CA_NMI,Len,Duplicate,MDM_Status,Never,HES,NMI Status,mdm_AMR,mdm_master_data_sync,Meter Replacement,Communicating,mdm_Notification,Commissioning_Tag,Remarks,Detailed_Remarks,Mobile Number,Utility Name,Replacement Date,Aging,Bucket,Bucket1,Category Name,Type,Phase,Town,Origin_ID,Section_Name,Division_Name,Status,Vendor_Planner,Refurbished,Diff,2023-06-17 00:00:00,2024-06-17 00:00:00,fsdfaf,Refirbished,Check,Comments,Comment,Aging_Creation_Date,Aging_Creation_Date_BACKDATE,Year-Week,Week,Month,Agging_bucket_30,Resolved Cases,Count
0,CAFAB,edf_mi_verification_approved,Meter Replacement,100031180,5000129029,LT8071043,NaN,NaN,9,1,Installed,NaN,NaN,Y,Y,NaN,SUCCESS,NaN,NaN,Not Commissioned,Welcome Msg Not Sent,"NMI Success, AMR Not ""Y""",8500009678.0,SBPD,2024-03-29,4,04 - 07,04 - 07,NDS-IID(B),Prepaid,3.0,Jahanabad,AI Engineering,Sec-Jahanabad(W),Jehanabad,Closed,AI_vp_jahn01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-04-02,2024-03-25,2024-13,14,4,<=30,0,1
1,CAFAB,edf_mi_verification_approved,Meter Replacement,100044522,5000142166,LT0726329,NaN,NaN,9,1,Installed,Never Communicating Meter,NaN,Y,Y,Y,SUCCESS,NaN,NaN,Not Commissioned,Welcome Msg Not Sent,Never Communicating Meter,9905266864.0,SBPD,2022-11-13,506,>30,>180,DS-IID,Prepaid,1.0,Jahanabad,bhaskar_solar,Sec-Jahanabad(W),Jehanabad,Closed,bs_jahana_vp1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-04-02,2021-06-25,2024-13,14,4,>30,0,1

In [16]:
FINAL_DATA_ALL_MERGE.shape

(1502454, 54)

In [17]:
for i in range(2 , max(FINAL_DATA_ALL_MERGE['Week']) + 1):

    # PREVIOUS WEEK DATA
    previous_week_data = FINAL_DATA_ALL_MERGE[FINAL_DATA_ALL_MERGE['Week']== i-1]
    previous_week_data_count = previous_week_data['New Meter No'].count()

    # CURRENT WEEK DATA
    current_week_data = FINAL_DATA_ALL_MERGE[FINAL_DATA_ALL_MERGE['Week']== i]
    current_week_data_count = current_week_data['New Meter No'].count()

    #NEW METER IN CURRENT WEEK
    new_week_meter_data = current_week_data[~current_week_data['New Meter No'].isin(previous_week_data['New Meter No'])]
    new_week_meter_data_count = new_week_meter_data['New Meter No'].count()
    
    # RESOLVED CASES
    resolved_cases = previous_week_data[~previous_week_data['New Meter No'].isin(current_week_data['New Meter No'])]
    resolved_cases_data_count = resolved_cases['New Meter No'].count()

    print(f"PREVIOUS WEEK ({i-1}) METER DATA COUNT IS : {previous_week_data_count}")

    print(f"CURRENT WEEK ({i}) METER DATA COUNT IS :  {current_week_data_count}")

    print(f"NEW METER DATA COUNT IN CURRENT WEEK ({i}) :  {new_week_meter_data_count}")

    print(f"resolved METER DATA COUNT IN CURENT WEEK ({i}) from the last week({i-1}) :  {resolved_cases_data_count}")

    print('-' * 70)
    print('-' * 70)

PREVIOUS WEEK (1) METER DATA COUNT IS : 27991
CURRENT WEEK (2) METER DATA COUNT IS :  27227
NEW METER DATA COUNT IN CURRENT WEEK (2) :  6487
resolved METER DATA COUNT IN CURENT WEEK (2) from the last week(1) :  7201
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (2) METER DATA COUNT IS : 27227
CURRENT WEEK (3) METER DATA COUNT IS :  18799
NEW METER DATA COUNT IN CURRENT WEEK (3) :  3489
resolved METER DATA COUNT IN CURENT WEEK (3) from the last week(2) :  5914
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (3) METER DATA COUNT IS : 18799
CURRENT WEEK (4) METER DATA COUNT IS :  4906
NEW METER DATA COUNT IN CURRENT WEEK (4) :  801
resolved METER DATA COUNT IN CURENT WEEK (4) from the last week(3) :  7103
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (4) METER DATA COUNT IS : 4906
CURRENT WEEK (5) METER DATA COUNT IS :  22510
NEW METER DATA COUNT IN CURRENT WEEK (5) :  9050
resolved METER DATA COUNT IN CURENT WEEK (5) from the last week(4) :  1502
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (5) METER DATA COUNT IS : 22510
CURRENT WEEK (6) METER DATA COUNT IS :  46360
NEW METER DATA COUNT IN CURRENT WEEK (6) :  21789
resolved METER DATA COUNT IN CURENT WEEK (6) from the last week(5) :  7072
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (6) METER DATA COUNT IS : 46360
CURRENT WEEK (7) METER DATA COUNT IS :  49471
NEW METER DATA COUNT IN CURRENT WEEK (7) :  21173
resolved METER DATA COUNT IN CURENT WEEK (7) from the last week(6) :  20446
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (7) METER DATA COUNT IS : 49471
CURRENT WEEK (8) METER DATA COUNT IS :  49287
NEW METER DATA COUNT IN CURRENT WEEK (8) :  24414
resolved METER DATA COUNT IN CURENT WEEK (8) from the last week(7) :  31546
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (8) METER DATA COUNT IS : 49287
CURRENT WEEK (9) METER DATA COUNT IS :  43292
NEW METER DATA COUNT IN CURRENT WEEK (9) :  18146
resolved METER DATA COUNT IN CURENT WEEK (9) from the last week(8) :  23778
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (9) METER DATA COUNT IS : 43292
CURRENT WEEK (10) METER DATA COUNT IS :  29176
NEW METER DATA COUNT IN CURRENT WEEK (10) :  9463
resolved METER DATA COUNT IN CURENT WEEK (10) from the last week(9) :  21201
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (10) METER DATA COUNT IS : 29176
CURRENT WEEK (11) METER DATA COUNT IS :  31691
NEW METER DATA COUNT IN CURRENT WEEK (11) :  12712
resolved METER DATA COUNT IN CURENT WEEK (11) from the last week(10) :  14948
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (11) METER DATA COUNT IS : 31691
CURRENT WEEK (12) METER DATA COUNT IS :  24115
NEW METER DATA COUNT IN CURRENT WEEK (12) :  6371
resolved METER DATA COUNT IN CURENT WEEK (12) from the last week(11) :  14908
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (12) METER DATA COUNT IS : 24115
CURRENT WEEK (13) METER DATA COUNT IS :  8636
NEW METER DATA COUNT IN CURRENT WEEK (13) :  2016
resolved METER DATA COUNT IN CURENT WEEK (13) from the last week(12) :  9240
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (13) METER DATA COUNT IS : 8636
CURRENT WEEK (14) METER DATA COUNT IS :  22675
NEW METER DATA COUNT IN CURRENT WEEK (14) :  6000
resolved METER DATA COUNT IN CURENT WEEK (14) from the last week(13) :  1263
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (14) METER DATA COUNT IS : 22675
CURRENT WEEK (15) METER DATA COUNT IS :  13729
NEW METER DATA COUNT IN CURRENT WEEK (15) :  4027
resolved METER DATA COUNT IN CURENT WEEK (15) from the last week(14) :  10835
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (15) METER DATA COUNT IS : 13729
CURRENT WEEK (16) METER DATA COUNT IS :  15731
NEW METER DATA COUNT IN CURRENT WEEK (16) :  3938
resolved METER DATA COUNT IN CURENT WEEK (16) from the last week(15) :  4802
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (16) METER DATA COUNT IS : 15731
CURRENT WEEK (17) METER DATA COUNT IS :  24543
NEW METER DATA COUNT IN CURRENT WEEK (17) :  7722
resolved METER DATA COUNT IN CURENT WEEK (17) from the last week(16) :  1947
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (17) METER DATA COUNT IS : 24543
CURRENT WEEK (18) METER DATA COUNT IS :  10303
NEW METER DATA COUNT IN CURRENT WEEK (18) :  2128
resolved METER DATA COUNT IN CURENT WEEK (18) from the last week(17) :  5751
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (18) METER DATA COUNT IS : 10303
CURRENT WEEK (19) METER DATA COUNT IS :  47521
NEW METER DATA COUNT IN CURRENT WEEK (19) :  32771
resolved METER DATA COUNT IN CURENT WEEK (19) from the last week(18) :  4571
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (19) METER DATA COUNT IS : 47521
CURRENT WEEK (20) METER DATA COUNT IS :  65413
NEW METER DATA COUNT IN CURRENT WEEK (20) :  17932
resolved METER DATA COUNT IN CURENT WEEK (20) from the last week(19) :  7984
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (20) METER DATA COUNT IS : 65413
CURRENT WEEK (21) METER DATA COUNT IS :  48348
NEW METER DATA COUNT IN CURRENT WEEK (21) :  11625
resolved METER DATA COUNT IN CURENT WEEK (21) from the last week(20) :  9334
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (21) METER DATA COUNT IS : 48348
CURRENT WEEK (22) METER DATA COUNT IS :  39647
NEW METER DATA COUNT IN CURRENT WEEK (22) :  5458
resolved METER DATA COUNT IN CURENT WEEK (22) from the last week(21) :  16624
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (22) METER DATA COUNT IS : 39647
CURRENT WEEK (23) METER DATA COUNT IS :  76307
NEW METER DATA COUNT IN CURRENT WEEK (23) :  20802
resolved METER DATA COUNT IN CURENT WEEK (23) from the last week(22) :  7394
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (23) METER DATA COUNT IS : 76307
CURRENT WEEK (24) METER DATA COUNT IS :  69915
NEW METER DATA COUNT IN CURRENT WEEK (24) :  14445
resolved METER DATA COUNT IN CURENT WEEK (24) from the last week(23) :  6786
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (24) METER DATA COUNT IS : 69915
CURRENT WEEK (25) METER DATA COUNT IS :  75988
NEW METER DATA COUNT IN CURRENT WEEK (25) :  16200
resolved METER DATA COUNT IN CURENT WEEK (25) from the last week(24) :  22949
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (25) METER DATA COUNT IS : 75988
CURRENT WEEK (26) METER DATA COUNT IS :  62666
NEW METER DATA COUNT IN CURRENT WEEK (26) :  17232
resolved METER DATA COUNT IN CURENT WEEK (26) from the last week(25) :  28045
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (26) METER DATA COUNT IS : 62666
CURRENT WEEK (27) METER DATA COUNT IS :  43641
NEW METER DATA COUNT IN CURRENT WEEK (27) :  12898
resolved METER DATA COUNT IN CURENT WEEK (27) from the last week(26) :  20445
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (27) METER DATA COUNT IS : 43641
CURRENT WEEK (28) METER DATA COUNT IS :  65492
NEW METER DATA COUNT IN CURRENT WEEK (28) :  21693
resolved METER DATA COUNT IN CURENT WEEK (28) from the last week(27) :  9945
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (28) METER DATA COUNT IS : 65492
CURRENT WEEK (29) METER DATA COUNT IS :  69634
NEW METER DATA COUNT IN CURRENT WEEK (29) :  20351
resolved METER DATA COUNT IN CURENT WEEK (29) from the last week(28) :  18949
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (29) METER DATA COUNT IS : 69634
CURRENT WEEK (30) METER DATA COUNT IS :  53370
NEW METER DATA COUNT IN CURRENT WEEK (30) :  20342
resolved METER DATA COUNT IN CURENT WEEK (30) from the last week(29) :  36949
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (30) METER DATA COUNT IS : 53370
CURRENT WEEK (31) METER DATA COUNT IS :  52662
NEW METER DATA COUNT IN CURRENT WEEK (31) :  22338
resolved METER DATA COUNT IN CURENT WEEK (31) from the last week(30) :  18413
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (31) METER DATA COUNT IS : 52662
CURRENT WEEK (32) METER DATA COUNT IS :  53613
NEW METER DATA COUNT IN CURRENT WEEK (32) :  26101
resolved METER DATA COUNT IN CURENT WEEK (32) from the last week(31) :  21458
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (32) METER DATA COUNT IS : 53613
CURRENT WEEK (33) METER DATA COUNT IS :  41489
NEW METER DATA COUNT IN CURRENT WEEK (33) :  14774
resolved METER DATA COUNT IN CURENT WEEK (33) from the last week(32) :  24685
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (33) METER DATA COUNT IS : 41489
CURRENT WEEK (34) METER DATA COUNT IS :  38047
NEW METER DATA COUNT IN CURRENT WEEK (34) :  11841
resolved METER DATA COUNT IN CURENT WEEK (34) from the last week(33) :  15796
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (34) METER DATA COUNT IS : 38047
CURRENT WEEK (35) METER DATA COUNT IS :  35845
NEW METER DATA COUNT IN CURRENT WEEK (35) :  13473
resolved METER DATA COUNT IN CURENT WEEK (35) from the last week(34) :  15198
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (35) METER DATA COUNT IS : 35845
CURRENT WEEK (36) METER DATA COUNT IS :  50683
NEW METER DATA COUNT IN CURRENT WEEK (36) :  22635
resolved METER DATA COUNT IN CURENT WEEK (36) from the last week(35) :  13749
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (36) METER DATA COUNT IS : 50683
CURRENT WEEK (37) METER DATA COUNT IS :  35228
NEW METER DATA COUNT IN CURRENT WEEK (37) :  13230
resolved METER DATA COUNT IN CURENT WEEK (37) from the last week(36) :  23404
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (37) METER DATA COUNT IS : 35228
CURRENT WEEK (38) METER DATA COUNT IS :  6503
NEW METER DATA COUNT IN CURRENT WEEK (38) :  1200
resolved METER DATA COUNT IN CURENT WEEK (38) from the last week(37) :  13599
----------------------------------------------------------------------
----------------------------------------------------------------------

In [18]:
FINAL_DATA_ALL_MERGE.head(3)

,Section ID,WO Status,Work Order Type,Consumer ID,installation_number,New Meter No,S2S Meter,CA_NMI,Len,Duplicate,MDM_Status,Never,HES,NMI Status,mdm_AMR,mdm_master_data_sync,Meter Replacement,Communicating,mdm_Notification,Commissioning_Tag,Remarks,Detailed_Remarks,Mobile Number,Utility Name,Replacement Date,Aging,Bucket,Bucket1,Category Name,Type,Phase,Town,Origin_ID,Section_Name,Division_Name,Status,Vendor_Planner,Refurbished,Diff,2023-06-17 00:00:00,2024-06-17 00:00:00,fsdfaf,Refirbished,Check,Comments,Comment,Aging_Creation_Date,Aging_Creation_Date_BACKDATE,Year-Week,Week,Month,Agging_bucket_30,Resolved Cases,Count
0,CAFAB,edf_mi_verification_approved,Meter Replacement,100031180,5000129029,LT8071043,NaN,NaN,9,1,Installed,NaN,NaN,Y,Y,NaN,SUCCESS,NaN,NaN,Not Commissioned,Welcome Msg Not Sent,"NMI Success, AMR Not ""Y""",8500009678.0,SBPD,2024-03-29,4,04 - 07,04 - 07,NDS-IID(B),Prepaid,3.0,Jahanabad,AI Engineering,Sec-Jahanabad(W),Jehanabad,Closed,AI_vp_jahn01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-04-02,2024-03-25,2024-13,14,4,<=30,0,1
1,CAFAB,edf_mi_verification_approved,Meter Replacement,100044522,5000142166,LT0726329,NaN,NaN,9,1,Installed,Never Communicating Meter,NaN,Y,Y,Y,SUCCESS,NaN,NaN,Not Commissioned,Welcome Msg Not Sent,Never Communicating Meter,9905266864.0,SBPD,2022-11-13,506,>30,>180,DS-IID,Prepaid,1.0,Jahanabad,bhaskar_solar,Sec-Jahanabad(W),Jehanabad,Closed,bs_jahana_vp1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-04-02,2021-06-25,2024-13,14,4,>30,0,1
2,DBAAB,MI Complete,Meter Replacement,100058065,5000155837,GL9094042,NaN,NaN,9,1,Meter Shop,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Welcome Msg Not Sent,Work Order Not Closed,8409104679.0,SBPD,2024-03-31,2,0 - 03,02 - 03,DS-IID,Prepaid,1.0,Munger,ss_infoline,Sec-Lal Darwaja,Munger,Open,ssi_vp_18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-04-02,2024-03-29,2024-13,14,4,<=30,0,1

In [19]:
FINAL_DATA_ALL_MERGE['Detailed_Remarks'].unique()

array(['NMI Success, AMR Not "Y"', 'Never Communicating Meter',
       'Work Order Not Closed', 'AMR "Y" but MR Pending', 'PD',
       'Communicating not "Y" in MDM',
       'Welcome Notification Sent from MDM but not from SCM',
       'Never Communicating Meter (O&M-IT)', 'Reason to be Checked',
       'Work Order Closed but not installed in MDM', 'Mismatch Case',
       'Duplicate Meter',
       'Daily read received in HES, Issue not related to HES',
       'Welcome Notification Not Sent from MDM',
       'Installed in MDM but CA not Assigned from DISCOM',
       'Never Communicating Meter (DISCOM)', 'Wrong Meter Number',
       'Never Communicating Meter (O&MIT)',
       'Welcome Notification not Sent from MDM',
       'NMI Success, AMR Not "Y", MR Success and DP Received',
       'NMI Success, AMR Not "Y", MR Success and DP Not Received',
       'Not Commissioned',
       'NMI Success, AMR Not "Y", MR Pending and DP Received',
       'Only AMR "Y"',
       'NMI Success, AMR Not "Y", MR Pending and DP Not Received',
       'Only DP Received', 'Commissioned',
       'AMR "Y", MR Success but DP Not Received',
       'AMR Not "Y" but MR Success and DP Received',
       'AMR Not "Y" but MR Success and DP Not Received',
       'AMR "Y" but MR Success and DP Not Received',
       'DP Received but MR Pending', 'DP Received but MR Success',
       'Mutation Case, New CA Not Updated in WFM', 'MR Pending',
       'MR Success but DP Not Received'], dtype=object)

In [20]:
FINAL_DATA_ALL_MERGE.columns

Index(['Section ID', 'WO Status', 'Work Order Type', 'Consumer ID',
       'installation_number', 'New Meter No', 'S2S Meter', 'CA_NMI', 'Len',
       'Duplicate', 'MDM_Status', 'Never', 'HES', 'NMI Status', 'mdm_AMR',
       'mdm_master_data_sync', 'Meter Replacement', 'Communicating',
       'mdm_Notification', 'Commissioning_Tag', 'Remarks', 'Detailed_Remarks',
       'Mobile Number', 'Utility Name', 'Replacement Date', 'Aging', 'Bucket',
       'Bucket1', 'Category Name', 'Type', 'Phase', 'Town', 'Origin_ID',
       'Section_Name', 'Division_Name', 'Status', 'Vendor_Planner',
       'Refurbished', 'Diff', '2023-06-17 00:00:00', '2024-06-17 00:00:00',
       'fsdfaf', 'Refirbished', 'Check', 'Comments', 'Comment',
       'Aging_Creation_Date', 'Aging_Creation_Date_BACKDATE', 'Year-Week',
       'Week', 'Month', 'Agging_bucket_30', 'Resolved Cases', 'Count'],
      dtype='object')

In [21]:
FINAL_DATA_ALL_MERGE.head(2)

,Section ID,WO Status,Work Order Type,Consumer ID,installation_number,New Meter No,S2S Meter,CA_NMI,Len,Duplicate,MDM_Status,Never,HES,NMI Status,mdm_AMR,mdm_master_data_sync,Meter Replacement,Communicating,mdm_Notification,Commissioning_Tag,Remarks,Detailed_Remarks,Mobile Number,Utility Name,Replacement Date,Aging,Bucket,Bucket1,Category Name,Type,Phase,Town,Origin_ID,Section_Name,Division_Name,Status,Vendor_Planner,Refurbished,Diff,2023-06-17 00:00:00,2024-06-17 00:00:00,fsdfaf,Refirbished,Check,Comments,Comment,Aging_Creation_Date,Aging_Creation_Date_BACKDATE,Year-Week,Week,Month,Agging_bucket_30,Resolved Cases,Count
0,CAFAB,edf_mi_verification_approved,Meter Replacement,100031180,5000129029,LT8071043,NaN,NaN,9,1,Installed,NaN,NaN,Y,Y,NaN,SUCCESS,NaN,NaN,Not Commissioned,Welcome Msg Not Sent,"NMI Success, AMR Not ""Y""",8500009678.0,SBPD,2024-03-29,4,04 - 07,04 - 07,NDS-IID(B),Prepaid,3.0,Jahanabad,AI Engineering,Sec-Jahanabad(W),Jehanabad,Closed,AI_vp_jahn01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-04-02,2024-03-25,2024-13,14,4,<=30,0,1
1,CAFAB,edf_mi_verification_approved,Meter Replacement,100044522,5000142166,LT0726329,NaN,NaN,9,1,Installed,Never Communicating Meter,NaN,Y,Y,Y,SUCCESS,NaN,NaN,Not Commissioned,Welcome Msg Not Sent,Never Communicating Meter,9905266864.0,SBPD,2022-11-13,506,>30,>180,DS-IID,Prepaid,1.0,Jahanabad,bhaskar_solar,Sec-Jahanabad(W),Jehanabad,Closed,bs_jahana_vp1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-04-02,2021-06-25,2024-13,14,4,>30,0,1

In [22]:
# Step 3: Specify the columns you want in the new DataFrame
selected_columns = ['WO Status', 'Consumer ID','installation_number', 'New Meter No', 'S2S Meter','MDM_Status', 'Never', 'Meter Replacement', 'Aging_Creation_Date',
                    'Remarks', 'Detailed_Remarks', 'Utility Name', 'Replacement Date', 'Aging', 'Bucket',
       'Bucket1', 'Category Name', 'Type', 'Phase','Section_Name', 'Division_Name', 'Status',
       'Aging_Creation_Date_BACKDATE', 'Year-Week', 'Week', 'Month',
       'Agging_bucket_30', 'Resolved Cases', 'Count']

# Step 4: Create the new DataFrame with the selected columns
FINAL_DATA_ALL_MERGE = FINAL_DATA_ALL_MERGE[selected_columns]

In [23]:
FINAL_DATA_ALL_MERGE.columns

Index(['WO Status', 'Consumer ID', 'installation_number', 'New Meter No',
       'S2S Meter', 'MDM_Status', 'Never', 'Meter Replacement',
       'Aging_Creation_Date', 'Remarks', 'Detailed_Remarks', 'Utility Name',
       'Replacement Date', 'Aging', 'Bucket', 'Bucket1', 'Category Name',
       'Type', 'Phase', 'Section_Name', 'Division_Name', 'Status',
       'Aging_Creation_Date_BACKDATE', 'Year-Week', 'Week', 'Month',
       'Agging_bucket_30', 'Resolved Cases', 'Count'],
      dtype='object')

### final data all merge done to csv

In [24]:
FINAL_DATA_ALL_MERGE.to_csv(r"C:\Users\Ratan Kumar Jha\Desktop\welcome msg\ANALYSIS OUTPUT\FINAL_DATA_ALL_MERGE.csv")
FINAL_DATA_ALL_MERGE.to_csv(r"C:\Users\Ratan Kumar Jha\Desktop\welcome msg\ANALYSIS OUTPUT\FINAL_DATA\FINAL_DATA_ALL_MERGE.csv")

In [25]:
FINAL_DATA_ALL_MERGE.shape

(1502454, 29)

## creating a new column where count all the days in b/w the rows

In [26]:
FINAL_DATA_ALL_MERGE.columns

Index(['WO Status', 'Consumer ID', 'installation_number', 'New Meter No',
       'S2S Meter', 'MDM_Status', 'Never', 'Meter Replacement',
       'Aging_Creation_Date', 'Remarks', 'Detailed_Remarks', 'Utility Name',
       'Replacement Date', 'Aging', 'Bucket', 'Bucket1', 'Category Name',
       'Type', 'Phase', 'Section_Name', 'Division_Name', 'Status',
       'Aging_Creation_Date_BACKDATE', 'Year-Week', 'Week', 'Month',
       'Agging_bucket_30', 'Resolved Cases', 'Count'],
      dtype='object')

In [27]:
#FINAL_DATA_ALL_MERGE.to_csv(r"C:\Users\Ratan Kumar Jha\Desktop\welcome msg\ANALYSIS OUTPUT\FINAL_DATA_ALL_MERGE.csv")
FINAL_DATA_ALL_MERGE_MISSING_DAYS_COUNT = pd.read_csv(r"C:\Users\Ratan Kumar Jha\Desktop\welcome msg\ANALYSIS OUTPUT\FINAL_DATA_ALL_MERGE.csv")


FINAL_DATA_ALL_MERGE_MISSING_DAYS_COUNT['Aging_Creation_Date'] = pd.to_datetime(FINAL_DATA_ALL_MERGE_MISSING_DAYS_COUNT['Aging_Creation_Date'])


FINAL_DATA_ALL_MERGE_MISSING_DAYS_COUNT.drop(['WO Status',
        'S2S Meter',
        'MDM_Status', 'Never', 
        'Remarks',
       'Type', 'Phase', 
       'Section_Name', 'Division_Name', 'Status',
       'Unnamed: 0'],axis=1, inplace=True)

In [28]:
# Sort the records in ascending order based on New Meter No and Aging_Creation_Date
FINAL_DATA_ALL_MERGE_MISSING_DAYS_COUNT = FINAL_DATA_ALL_MERGE_MISSING_DAYS_COUNT.sort_values(['New Meter No', 'Aging_Creation_Date'], ascending=[True, True])

# Add lead status and lead date columns
FINAL_DATA_ALL_MERGE_MISSING_DAYS_COUNT['lead_status'] = FINAL_DATA_ALL_MERGE_MISSING_DAYS_COUNT.groupby('New Meter No')['Detailed_Remarks'].shift(-1)
FINAL_DATA_ALL_MERGE_MISSING_DAYS_COUNT['lead_date'] = FINAL_DATA_ALL_MERGE_MISSING_DAYS_COUNT.groupby('New Meter No')['Aging_Creation_Date'].shift(-1)

# Fill NaN values in lead_status and lead_date with current status and date
FINAL_DATA_ALL_MERGE_MISSING_DAYS_COUNT['lead_status'].fillna(FINAL_DATA_ALL_MERGE_MISSING_DAYS_COUNT['Detailed_Remarks'], inplace=True)
FINAL_DATA_ALL_MERGE_MISSING_DAYS_COUNT['lead_date'].fillna(FINAL_DATA_ALL_MERGE_MISSING_DAYS_COUNT['Aging_Creation_Date'], inplace=True)

# Calculate aging of status
FINAL_DATA_ALL_MERGE_MISSING_DAYS_COUNT['meter_aging'] = (FINAL_DATA_ALL_MERGE_MISSING_DAYS_COUNT['lead_date'] - FINAL_DATA_ALL_MERGE_MISSING_DAYS_COUNT['Aging_Creation_Date']).dt.days.fillna(1)
FINAL_DATA_ALL_MERGE_MISSING_DAYS_COUNT['meter_aging'] = FINAL_DATA_ALL_MERGE_MISSING_DAYS_COUNT['meter_aging'].where(FINAL_DATA_ALL_MERGE_MISSING_DAYS_COUNT['meter_aging'] > 0, 1)



#print(FINAL_DATA_ALL_MERGE)

C:\Users\Ratan Kumar Jha\AppData\Local\Temp\ipykernel_20404\676926761.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  FINAL_DATA_ALL_MERGE_MISSING_DAYS_COUNT['lead_status'].fillna(FINAL_DATA_ALL_MERGE_MISSING_DAYS_COUNT['Detailed_Remarks'], inplace=True)
C:\Users\Ratan Kumar Jha\AppData\Local\Temp\ipykernel_20404\676926761.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  FINAL_DATA_ALL_MERGE_MISSING_DAYS_COUNT['lead_date'].fillna(FINAL_DATA_ALL_MERGE_MISSING_DAYS_COUNT['Aging_Creation_Date'], inplace=True)

In [29]:
FINAL_DATA_ALL_MERGE_MISSING_DAYS_COUNT['Detailed_Remarks'].unique()

array(['Work Order Not Closed',
       'Installed in MDM but CA not Assigned from DISCOM',
       'NMI Success, AMR Not "Y", MR Success and DP Received',
       'NMI Success, AMR Not "Y", MR Success and DP Not Received',
       'Communicating not "Y" in MDM',
       'Never Communicating Meter (O&M-IT)',
       'Welcome Notification Sent from MDM but not from SCM',
       'NMI Success, AMR Not "Y"',
       'Welcome Notification Not Sent from MDM',
       'Never Communicating Meter',
       'Work Order Closed but not installed in MDM',
       'AMR "Y" but MR Pending', 'Only AMR "Y"', 'Not Commissioned',
       'AMR "Y", MR Success but DP Not Received',
       'NMI Success, AMR Not "Y", MR Pending and DP Not Received',
       'Never Communicating Meter (DISCOM)',
       'Never Communicating Meter (O&MIT)', 'Reason to be Checked',
       'AMR Not "Y" but MR Success and DP Not Received',
       'Welcome Notification not Sent from MDM',
       'NMI Success, AMR Not "Y", MR Pending and DP Received',
       'Mismatch Case', 'Only DP Received',
       'AMR "Y" but MR Success and DP Not Received',
       'MR Success but DP Not Received', 'Duplicate Meter', 'MR Pending',
       'PD', 'DP Received but MR Pending', 'Wrong Meter Number',
       'DP Received but MR Success',
       'Daily read received in HES, Issue not related to HES',
       'AMR Not "Y" but MR Success and DP Received', 'Commissioned',
       'Mutation Case, New CA Not Updated in WFM'], dtype=object)

In [30]:
FINAL_DATA_ALL_MERGE_MISSING_DAYS_COUNT.to_csv(r"C:\Users\Ratan Kumar Jha\Desktop\welcome msg\ANALYSIS OUTPUT\FINAL_DATA_ALL_MERGE_MISSING_DAYS_COUNT.csv")
FINAL_DATA_ALL_MERGE_MISSING_DAYS_COUNT.to_csv(r"C:\Users\Ratan Kumar Jha\Desktop\welcome msg\ANALYSIS OUTPUT\FINAL_DATA\FINAL_DATA_ALL_MERGE_MISSING_DAYS_COUNT.csv")

In [31]:
FINAL_DATA_ALL_MERGE_MISSING_DAYS_COUNT.shape

(1502454, 22)

In [32]:
FINAL_DATA_ALL_MERGE_MISSING_DAYS_COUNT.head(2)

,Consumer ID,installation_number,New Meter No,Meter Replacement,Aging_Creation_Date,Detailed_Remarks,Utility Name,Replacement Date,Aging,Bucket,Bucket1,Category Name,Aging_Creation_Date_BACKDATE,Year-Week,Week,Month,Agging_bucket_30,Resolved Cases,Count,lead_status,lead_date,meter_aging
408680,5004017369,5004017369,GL8548353,NaN,2024-02-23,Work Order Not Closed,NBPD,2024-02-22,1,0 - 03,00 - 01,DS-IID,2024-02-21,2024-07,8,2,<=30,0,1,Installed in MDM but CA not Assigned from DISCOM,2024-02-24,1
417385,5004017369,5004017369,GL8548353,SUCCESS,2024-02-24,Installed in MDM but CA not Assigned from DISCOM,NBPD,2024-02-22,2,0 - 03,02 - 03,DS-IID,2024-02-20,2024-07,8,2,<=30,0,1,"NMI Success, AMR Not ""Y"", MR Success and DP Re...",2024-02-26,2

### CREATING COLUMN  OF RESOLVED AND NEW METER DATA IN WELCOME_MSG_UNIQUE_RECORD

#### This code will create a unique record in all the week

In [33]:
import os
import pandas as pd

dataframe = []

for i in range(1, max(FINAL_DATA_ALL_MERGE['Week']) + 1):
    print(f"Data shape for week ({i}) is: {FINAL_DATA_ALL_MERGE[FINAL_DATA_ALL_MERGE['Week']==i].shape}")
    WEEK_WISE_UNIQUE_DATA = FINAL_DATA_ALL_MERGE[FINAL_DATA_ALL_MERGE['Week']==i].drop_duplicates(subset=['New Meter No'], keep='last').reset_index(drop=True)
    print(f"Data shape for week ({i}) is: {WEEK_WISE_UNIQUE_DATA.shape}")
    dataframe.append(WEEK_WISE_UNIQUE_DATA)

# Concatenate all DataFrames in the list along the rows

WELCOME_MSG_UNIQUE_RECORD = pd.concat(dataframe, ignore_index=True)
WELCOME_MSG_UNIQUE_RECORD.to_csv(r"C:\Users\Ratan Kumar Jha\Desktop\welcome msg\ANALYSIS OUTPUT\WELCOME_MSG_UNIQUE_RECORD.csv")

Data shape for week (1) is: (27991, 29)
Data shape for week (1) is: (8114, 29)
Data shape for week (2) is: (27227, 29)
Data shape for week (2) is: (8613, 29)
Data shape for week (3) is: (18799, 29)
Data shape for week (3) is: (7578, 29)
Data shape for week (4) is: (4906, 29)
Data shape for week (4) is: (4905, 29)
Data shape for week (5) is: (22510, 29)
Data shape for week (5) is: (7179, 29)
Data shape for week (6) is: (46360, 29)
Data shape for week (6) is: (12433, 29)
Data shape for week (7) is: (49471, 29)
Data shape for week (7) is: (14889, 29)
Data shape for week (8) is: (49287, 29)
Data shape for week (8) is: (13471, 29)
Data shape for week (9) is: (43292, 29)
Data shape for week (9) is: (12961, 29)
Data shape for week (10) is: (29176, 29)
Data shape for week (10) is: (9167, 29)
Data shape for week (11) is: (31691, 29)
Data shape for week (11) is: (10226, 29)
Data shape for week (12) is: (24115, 29)
Data shape for week (12) is: (6808, 29)
Data shape for week (13) is: (8636, 29)
Data shape for week (13) is: (4438, 29)
Data shape for week (14) is: (22675, 29)
Data shape for week (14) is: (5996, 29)
Data shape for week (15) is: (13729, 29)
Data shape for week (15) is: (4304, 29)
Data shape for week (16) is: (15731, 29)
Data shape for week (16) is: (3793, 29)
Data shape for week (17) is: (24543, 29)
Data shape for week (17) is: (5615, 29)
Data shape for week (18) is: (10303, 29)
Data shape for week (18) is: (5518, 29)
Data shape for week (19) is: (47521, 29)
Data shape for week (19) is: (12665, 29)
Data shape for week (20) is: (65413, 29)
Data shape for week (20) is: (16472, 29)
Data shape for week (21) is: (48348, 29)
Data shape for week (21) is: (19159, 29)
Data shape for week (22) is: (39647, 29)
Data shape for week (22) is: (14626, 29)
Data shape for week (23) is: (76307, 29)
Data shape for week (23) is: (17984, 29)
Data shape for week (24) is: (69915, 29)
Data shape for week (24) is: (22239, 29)
Data shape for week (25) is: (75988, 29)
Data shape for week (25) is: (19128, 29)
Data shape for week (26) is: (62666, 29)
Data shape for week (26) is: (18084, 29)
Data shape for week (27) is: (43641, 29)
Data shape for week (27) is: (16329, 29)
Data shape for week (28) is: (65492, 29)
Data shape for week (28) is: (16982, 29)
Data shape for week (29) is: (69634, 29)
Data shape for week (29) is: (17904, 29)
Data shape for week (30) is: (53370, 29)
Data shape for week (30) is: (15642, 29)
Data shape for week (31) is: (52662, 29)
Data shape for week (31) is: (16484, 29)
Data shape for week (32) is: (53613, 29)
Data shape for week (32) is: (16307, 29)
Data shape for week (33) is: (41489, 29)
Data shape for week (33) is: (14488, 29)
Data shape for week (34) is: (38047, 29)
Data shape for week (34) is: (12078, 29)
Data shape for week (35) is: (35845, 29)
Data shape for week (35) is: (12242, 29)
Data shape for week (36) is: (50683, 29)
Data shape for week (36) is: (12605, 29)
Data shape for week (37) is: (35228, 29)
Data shape for week (37) is: (13108, 29)
Data shape for week (38) is: (6503, 29)
Data shape for week (38) is: (6503, 29)

In [34]:
for i in range(2 , max(WELCOME_MSG_UNIQUE_RECORD['Week']) + 1):

    # PREVIOUS WEEK DATA
    previous_week_data = WELCOME_MSG_UNIQUE_RECORD[WELCOME_MSG_UNIQUE_RECORD['Week']== i-1]
    previous_week_data_count = previous_week_data['New Meter No'].count()

    # CURRENT WEEK DATA
    current_week_data = WELCOME_MSG_UNIQUE_RECORD[WELCOME_MSG_UNIQUE_RECORD['Week']== i]
    current_week_data_count = current_week_data['New Meter No'].count()

    #NEW METER IN CURRENT WEEK
    new_week_meter_data = current_week_data[~current_week_data['New Meter No'].isin(previous_week_data['New Meter No'])]
    new_week_meter_data_count = new_week_meter_data['New Meter No'].count()
    
    # RESOLVED CASES
    resolved_cases = previous_week_data[~previous_week_data['New Meter No'].isin(current_week_data['New Meter No'])]
    resolved_cases_data_count = resolved_cases['New Meter No'].count()

    print(f"PREVIOUS WEEK ({i-1}) METER DATA COUNT IS : {previous_week_data_count}")

    print(f"CURRENT WEEK ({i}) METER DATA COUNT IS :  {current_week_data_count}")

    print(f"NEW METER DATA COUNT IN CURRENT WEEK ({i}) :  {new_week_meter_data_count}")

    print(f"resolved METER DATA COUNT IN CURENT WEEK ({i}) from the last week({i-1}) :  {resolved_cases_data_count}")

    print('-' * 70)
    print('-' * 70)

PREVIOUS WEEK (1) METER DATA COUNT IS : 8114
CURRENT WEEK (2) METER DATA COUNT IS :  8613
NEW METER DATA COUNT IN CURRENT WEEK (2) :  3112
resolved METER DATA COUNT IN CURENT WEEK (2) from the last week(1) :  2613
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (2) METER DATA COUNT IS : 8613
CURRENT WEEK (3) METER DATA COUNT IS :  7578
NEW METER DATA COUNT IN CURRENT WEEK (3) :  1821
resolved METER DATA COUNT IN CURENT WEEK (3) from the last week(2) :  2856
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (3) METER DATA COUNT IS : 7578
CURRENT WEEK (4) METER DATA COUNT IS :  4905
NEW METER DATA COUNT IN CURRENT WEEK (4) :  801
resolved METER DATA COUNT IN CURENT WEEK (4) from the last week(3) :  3474
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (4) METER DATA COUNT IS : 4905
CURRENT WEEK (5) METER DATA COUNT IS :  7179
NEW METER DATA COUNT IN CURRENT WEEK (5) :  3776
resolved METER DATA COUNT IN CURENT WEEK (5) from the last week(4) :  1502
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (5) METER DATA COUNT IS : 7179
CURRENT WEEK (6) METER DATA COUNT IS :  12433
NEW METER DATA COUNT IN CURRENT WEEK (6) :  7758
resolved METER DATA COUNT IN CURENT WEEK (6) from the last week(5) :  2504
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (6) METER DATA COUNT IS : 12433
CURRENT WEEK (7) METER DATA COUNT IS :  14889
NEW METER DATA COUNT IN CURRENT WEEK (7) :  8523
resolved METER DATA COUNT IN CURENT WEEK (7) from the last week(6) :  6067
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (7) METER DATA COUNT IS : 14889
CURRENT WEEK (8) METER DATA COUNT IS :  13471
NEW METER DATA COUNT IN CURRENT WEEK (8) :  8477
resolved METER DATA COUNT IN CURENT WEEK (8) from the last week(7) :  9895
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (8) METER DATA COUNT IS : 13471
CURRENT WEEK (9) METER DATA COUNT IS :  12961
NEW METER DATA COUNT IN CURRENT WEEK (9) :  7283
resolved METER DATA COUNT IN CURENT WEEK (9) from the last week(8) :  7793
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (9) METER DATA COUNT IS : 12961
CURRENT WEEK (10) METER DATA COUNT IS :  9167
NEW METER DATA COUNT IN CURRENT WEEK (10) :  3764
resolved METER DATA COUNT IN CURENT WEEK (10) from the last week(9) :  7558
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (10) METER DATA COUNT IS : 9167
CURRENT WEEK (11) METER DATA COUNT IS :  10226
NEW METER DATA COUNT IN CURRENT WEEK (11) :  5891
resolved METER DATA COUNT IN CURENT WEEK (11) from the last week(10) :  4832
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (11) METER DATA COUNT IS : 10226
CURRENT WEEK (12) METER DATA COUNT IS :  6808
NEW METER DATA COUNT IN CURRENT WEEK (12) :  2539
resolved METER DATA COUNT IN CURENT WEEK (12) from the last week(11) :  5957
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (12) METER DATA COUNT IS : 6808
CURRENT WEEK (13) METER DATA COUNT IS :  4438
NEW METER DATA COUNT IN CURRENT WEEK (13) :  1124
resolved METER DATA COUNT IN CURENT WEEK (13) from the last week(12) :  3494
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (13) METER DATA COUNT IS : 4438
CURRENT WEEK (14) METER DATA COUNT IS :  5996
NEW METER DATA COUNT IN CURRENT WEEK (14) :  2222
resolved METER DATA COUNT IN CURENT WEEK (14) from the last week(13) :  664
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (14) METER DATA COUNT IS : 5996
CURRENT WEEK (15) METER DATA COUNT IS :  4304
NEW METER DATA COUNT IN CURRENT WEEK (15) :  1744
resolved METER DATA COUNT IN CURENT WEEK (15) from the last week(14) :  3436
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (15) METER DATA COUNT IS : 4304
CURRENT WEEK (16) METER DATA COUNT IS :  3793
NEW METER DATA COUNT IN CURRENT WEEK (16) :  1349
resolved METER DATA COUNT IN CURENT WEEK (16) from the last week(15) :  1860
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (16) METER DATA COUNT IS : 3793
CURRENT WEEK (17) METER DATA COUNT IS :  5615
NEW METER DATA COUNT IN CURRENT WEEK (17) :  2489
resolved METER DATA COUNT IN CURENT WEEK (17) from the last week(16) :  667
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (17) METER DATA COUNT IS : 5615
CURRENT WEEK (18) METER DATA COUNT IS :  5518
NEW METER DATA COUNT IN CURRENT WEEK (18) :  1423
resolved METER DATA COUNT IN CURENT WEEK (18) from the last week(17) :  1520
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (18) METER DATA COUNT IS : 5518
CURRENT WEEK (19) METER DATA COUNT IS :  12665
NEW METER DATA COUNT IN CURRENT WEEK (19) :  9679
resolved METER DATA COUNT IN CURENT WEEK (19) from the last week(18) :  2532
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (19) METER DATA COUNT IS : 12665
CURRENT WEEK (20) METER DATA COUNT IS :  16472
NEW METER DATA COUNT IN CURRENT WEEK (20) :  5729
resolved METER DATA COUNT IN CURENT WEEK (20) from the last week(19) :  1922
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (20) METER DATA COUNT IS : 16472
CURRENT WEEK (21) METER DATA COUNT IS :  19159
NEW METER DATA COUNT IN CURRENT WEEK (21) :  5806
resolved METER DATA COUNT IN CURENT WEEK (21) from the last week(20) :  3119
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (21) METER DATA COUNT IS : 19159
CURRENT WEEK (22) METER DATA COUNT IS :  14626
NEW METER DATA COUNT IN CURRENT WEEK (22) :  2736
resolved METER DATA COUNT IN CURENT WEEK (22) from the last week(21) :  7269
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (22) METER DATA COUNT IS : 14626
CURRENT WEEK (23) METER DATA COUNT IS :  17984
NEW METER DATA COUNT IN CURRENT WEEK (23) :  6630
resolved METER DATA COUNT IN CURENT WEEK (23) from the last week(22) :  3272
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (23) METER DATA COUNT IS : 17984
CURRENT WEEK (24) METER DATA COUNT IS :  22239
NEW METER DATA COUNT IN CURRENT WEEK (24) :  6738
resolved METER DATA COUNT IN CURENT WEEK (24) from the last week(23) :  2483
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (24) METER DATA COUNT IS : 22239
CURRENT WEEK (25) METER DATA COUNT IS :  19128
NEW METER DATA COUNT IN CURRENT WEEK (25) :  6810
resolved METER DATA COUNT IN CURENT WEEK (25) from the last week(24) :  9921
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (25) METER DATA COUNT IS : 19128
CURRENT WEEK (26) METER DATA COUNT IS :  18084
NEW METER DATA COUNT IN CURRENT WEEK (26) :  6980
resolved METER DATA COUNT IN CURENT WEEK (26) from the last week(25) :  8024
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (26) METER DATA COUNT IS : 18084
CURRENT WEEK (27) METER DATA COUNT IS :  16329
NEW METER DATA COUNT IN CURRENT WEEK (27) :  6660
resolved METER DATA COUNT IN CURENT WEEK (27) from the last week(26) :  8415
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (27) METER DATA COUNT IS : 16329
CURRENT WEEK (28) METER DATA COUNT IS :  16982
NEW METER DATA COUNT IN CURRENT WEEK (28) :  7108
resolved METER DATA COUNT IN CURENT WEEK (28) from the last week(27) :  6455
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (28) METER DATA COUNT IS : 16982
CURRENT WEEK (29) METER DATA COUNT IS :  17904
NEW METER DATA COUNT IN CURRENT WEEK (29) :  6234
resolved METER DATA COUNT IN CURENT WEEK (29) from the last week(28) :  5312
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (29) METER DATA COUNT IS : 17904
CURRENT WEEK (30) METER DATA COUNT IS :  15642
NEW METER DATA COUNT IN CURRENT WEEK (30) :  8310
resolved METER DATA COUNT IN CURENT WEEK (30) from the last week(29) :  10572
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (30) METER DATA COUNT IS : 15642
CURRENT WEEK (31) METER DATA COUNT IS :  16484
NEW METER DATA COUNT IN CURRENT WEEK (31) :  8526
resolved METER DATA COUNT IN CURENT WEEK (31) from the last week(30) :  7684
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (31) METER DATA COUNT IS : 16484
CURRENT WEEK (32) METER DATA COUNT IS :  16307
NEW METER DATA COUNT IN CURRENT WEEK (32) :  8598
resolved METER DATA COUNT IN CURENT WEEK (32) from the last week(31) :  8775
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (32) METER DATA COUNT IS : 16307
CURRENT WEEK (33) METER DATA COUNT IS :  14488
NEW METER DATA COUNT IN CURRENT WEEK (33) :  7109
resolved METER DATA COUNT IN CURENT WEEK (33) from the last week(32) :  8928
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (33) METER DATA COUNT IS : 14488
CURRENT WEEK (34) METER DATA COUNT IS :  12078
NEW METER DATA COUNT IN CURRENT WEEK (34) :  5604
resolved METER DATA COUNT IN CURENT WEEK (34) from the last week(33) :  8014
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (34) METER DATA COUNT IS : 12078
CURRENT WEEK (35) METER DATA COUNT IS :  12242
NEW METER DATA COUNT IN CURRENT WEEK (35) :  6853
resolved METER DATA COUNT IN CURENT WEEK (35) from the last week(34) :  6689
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (35) METER DATA COUNT IS : 12242
CURRENT WEEK (36) METER DATA COUNT IS :  12605
NEW METER DATA COUNT IN CURRENT WEEK (36) :  7241
resolved METER DATA COUNT IN CURENT WEEK (36) from the last week(35) :  6878
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (36) METER DATA COUNT IS : 12605
CURRENT WEEK (37) METER DATA COUNT IS :  13108
NEW METER DATA COUNT IN CURRENT WEEK (37) :  7244
resolved METER DATA COUNT IN CURENT WEEK (37) from the last week(36) :  6741
----------------------------------------------------------------------
----------------------------------------------------------------------
PREVIOUS WEEK (37) METER DATA COUNT IS : 13108
CURRENT WEEK (38) METER DATA COUNT IS :  6503
NEW METER DATA COUNT IN CURRENT WEEK (38) :  1200
resolved METER DATA COUNT IN CURENT WEEK (38) from the last week(37) :  7805
----------------------------------------------------------------------
----------------------------------------------------------------------

## code  for New meter

##### New meter in week: 99 denotes new meter. it will replace by 1 and other values like 1,2,3 replace by 0

In [35]:

WELCOME_MSG_UNIQUE_RECORD_FIRST_WEEK = WELCOME_MSG_UNIQUE_RECORD[WELCOME_MSG_UNIQUE_RECORD['Week']==min(WELCOME_MSG_UNIQUE_RECORD['Week'].unique())]

dataframe = []
dataframe.append(WELCOME_MSG_UNIQUE_RECORD_FIRST_WEEK)

for i in range(2 , max(WELCOME_MSG_UNIQUE_RECORD['Week']) + 1):

    # PREVIOUS WEEK DATA
    previous_week_data = WELCOME_MSG_UNIQUE_RECORD[WELCOME_MSG_UNIQUE_RECORD['Week'] == i-1]
    #previous_week_data_count = previous_week_data['New Meter No'].count()

    # CURRENT WEEK DATA
    current_week_data = WELCOME_MSG_UNIQUE_RECORD[WELCOME_MSG_UNIQUE_RECORD['Week'] == i]
    #current_week_data_count = current_week_data['New Meter No'].count()

    MERGE_CURRENT_PREVIOUS_DATA = pd.merge(current_week_data,previous_week_data[['New Meter No','Week']],left_on=['New Meter No'], right_on=['New Meter No'], how='left')
    
    # after join which are blank fill them with 99
    MERGE_CURRENT_PREVIOUS_DATA['Week_y'] = MERGE_CURRENT_PREVIOUS_DATA['Week_y'].fillna(99)
    MERGE_CURRENT_PREVIOUS_DATA['Week_y'] = MERGE_CURRENT_PREVIOUS_DATA['Week_y'].astype(int)




    dataframe.append(MERGE_CURRENT_PREVIOUS_DATA)

# Concatenate all DataFrames in the list along the rows
MERGE_CURRENT_PREVIOUS_DATA = pd.concat(dataframe, ignore_index=True)

# fill 1 in week_x null rows.  bcz while calculating and appending the first week data. it show null
# fill 99 in the week_y null rows. bcz these are related to week 1. and will replace 99 by 1 . and other value by 0
# 1 indicate new value and 0 indicate old meter

MERGE_CURRENT_PREVIOUS_DATA['Week_x'] = MERGE_CURRENT_PREVIOUS_DATA['Week_x'].fillna(min(MERGE_CURRENT_PREVIOUS_DATA['Week'].unique()))
MERGE_CURRENT_PREVIOUS_DATA['Week_y'] = MERGE_CURRENT_PREVIOUS_DATA['Week_y'].fillna(99)

# data change to int type
MERGE_CURRENT_PREVIOUS_DATA['Week_x'] = MERGE_CURRENT_PREVIOUS_DATA['Week_x'].astype(int)
MERGE_CURRENT_PREVIOUS_DATA['Week_y'] = MERGE_CURRENT_PREVIOUS_DATA['Week_y'].astype(int)


MERGE_CURRENT_PREVIOUS_DATA.drop(columns=['Week'], inplace=True)
MERGE_CURRENT_PREVIOUS_DATA.rename(
    columns = {"Week_x":"Week","Week_y":"NEW_METER_COUNT"},inplace=True)


#MERGE_CURRENT_PREVIOUS_DATA['New_meter_count_per_week'] = MERGE_CURRENT_PREVIOUS_DATA['New_meter_count_per_week'].replace(99, 1).apply(lambda x: 0 if x != 1 else x)
# Output data file 

MERGE_CURRENT_PREVIOUS_DATA.to_csv(r"C:\Users\Ratan Kumar Jha\Desktop\welcome msg\ANALYSIS OUTPUT\MERGE_CURRENT_PREVIOUS_DATA.csv")

In [36]:
MERGE_CURRENT_PREVIOUS_DATA.head(2)

,WO Status,Consumer ID,installation_number,New Meter No,S2S Meter,MDM_Status,Never,Meter Replacement,Aging_Creation_Date,Remarks,Detailed_Remarks,Utility Name,Replacement Date,Aging,Bucket,Bucket1,Category Name,Type,Phase,Section_Name,Division_Name,Status,Aging_Creation_Date_BACKDATE,Year-Week,Month,Agging_bucket_30,Resolved Cases,Count,Week,NEW_METER_COUNT
0,edf_mi_verification_approved,101032204,5001980022,LT8058742,NaN,Installed,NaN,SUCCESS,2024-01-02,Welcome Msg Not Sent,"Communicating not ""Y"" in MDM",SBPD,2023-12-29,4,04 - 07,04 - 07,DS-IID,Prepaid,3.0,Sec-Rajapur,Pataliputra,Closed,2023-12-25,2024-00,1,<=30,0,1,1,99
1,edf_mi_verification_approved,101292593,5002100094,LT8069536,NaN,Installed,NaN,SUCCESS,2024-01-02,Welcome Msg Not Sent,"Communicating not ""Y"" in MDM",SBPD,2023-12-28,5,04 - 07,04 - 07,DS-IID,Prepaid,3.0,Sec-Buddha Colony,New Capital,Closed,2023-12-23,2024-00,1,<=30,0,1,1,99

In [37]:
min(MERGE_CURRENT_PREVIOUS_DATA['Week'].unique())

1

## code for  resolved meter

In [38]:

WELCOME_MSG_LAST_WEEK_RECORD = MERGE_CURRENT_PREVIOUS_DATA[MERGE_CURRENT_PREVIOUS_DATA['Week']== max(MERGE_CURRENT_PREVIOUS_DATA['Week'].unique())]

dataframe = []
#dataframe.append(WELCOME_MSG_UNIQUE_RECORD_FIRST_WEEK)

for i in range(2 , max(MERGE_CURRENT_PREVIOUS_DATA['Week']) + 1):

    # PREVIOUS WEEK DATA
    previous_week_data = MERGE_CURRENT_PREVIOUS_DATA[MERGE_CURRENT_PREVIOUS_DATA['Week'] == i-1]
  

    # CURRENT WEEK DATA
    current_week_data = MERGE_CURRENT_PREVIOUS_DATA[MERGE_CURRENT_PREVIOUS_DATA['Week'] == i]


    RESOLVED_METER_DATA = pd.merge(previous_week_data,current_week_data[['New Meter No','Week']],left_on=['New Meter No'], right_on=['New Meter No'], how='left')
    RESOLVED_METER_DATA['Week_y'] = RESOLVED_METER_DATA['Week_y'].fillna(99)
    RESOLVED_METER_DATA['Week_y'] = RESOLVED_METER_DATA['Week_y'].astype(int)




    dataframe.append(RESOLVED_METER_DATA)

dataframe.append(WELCOME_MSG_LAST_WEEK_RECORD)
# Concatenate all DataFrames in the list along the rows
RESOLVED_METER_DATA = pd.concat(dataframe, ignore_index=True)


# fill 15 in week_x null rows.  bcz while calculating and appending the LAST week data. it show null
# fill 0 in the week_y null rows. BCZ IN 15 WEEK THERE IS NO RESOLVED METER

RESOLVED_METER_DATA['Week_x'] = RESOLVED_METER_DATA['Week_x'].fillna(max(MERGE_CURRENT_PREVIOUS_DATA['Week'].unique()))
RESOLVED_METER_DATA['Week_y'] = RESOLVED_METER_DATA['Week_y'].fillna(0)

# data change to int type
RESOLVED_METER_DATA['Week_x'] = RESOLVED_METER_DATA['Week_x'].astype(int)
RESOLVED_METER_DATA['Week_y'] = RESOLVED_METER_DATA['Week_y'].astype(int)


RESOLVED_METER_DATA.drop(columns=['Week'], inplace=True)
RESOLVED_METER_DATA.rename(
    columns = {"Week_x":"Week","Week_y":"RESOLVED_METER_COUNT"},inplace=True)


#MERGE_CURRENT_PREVIOUS_DATA['New_meter_count_per_week'] = MERGE_CURRENT_PREVIOUS_DATA['New_meter_count_per_week'].replace(99, 1).apply(lambda x: 0 if x != 1 else x)
# Output data file 

RESOLVED_METER_DATA.to_csv(r"C:\Users\Ratan Kumar Jha\Desktop\welcome msg\ANALYSIS OUTPUT\RESOLVED_METER_DATA.csv")

In [39]:
RESOLVED_METER_DATA.head(1)

,WO Status,Consumer ID,installation_number,New Meter No,S2S Meter,MDM_Status,Never,Meter Replacement,Aging_Creation_Date,Remarks,Detailed_Remarks,Utility Name,Replacement Date,Aging,Bucket,Bucket1,Category Name,Type,Phase,Section_Name,Division_Name,Status,Aging_Creation_Date_BACKDATE,Year-Week,Month,Agging_bucket_30,Resolved Cases,Count,Week,NEW_METER_COUNT,RESOLVED_METER_COUNT
0,edf_mi_verification_approved,101032204,5001980022,LT8058742,NaN,Installed,NaN,SUCCESS,2024-01-02,Welcome Msg Not Sent,"Communicating not ""Y"" in MDM",SBPD,2023-12-29,4,04 - 07,04 - 07,DS-IID,Prepaid,3.0,Sec-Rajapur,Pataliputra,Closed,2023-12-25,2024-00,1,<=30,0,1,1,99,99

In [40]:
# Replace values other than 99 with 0 in the NEW_METER_COUNT column
RESOLVED_METER_DATA.loc[RESOLVED_METER_DATA['NEW_METER_COUNT'] != 99, 'NEW_METER_COUNT'] = 0
RESOLVED_METER_DATA.loc[RESOLVED_METER_DATA['RESOLVED_METER_COUNT'] != 99, 'RESOLVED_METER_COUNT'] = 0
RESOLVED_METER_DATA.loc[RESOLVED_METER_DATA['NEW_METER_COUNT'] == 99, 'NEW_METER_COUNT'] = 1
RESOLVED_METER_DATA.loc[RESOLVED_METER_DATA['RESOLVED_METER_COUNT'] == 99, 'RESOLVED_METER_COUNT'] = 1

In [41]:
RESOLVED_METER_DATA.to_csv(r"C:\Users\Ratan Kumar Jha\Desktop\welcome msg\ANALYSIS OUTPUT\RESOLVED_METER_DATA_FINAL_DATA.csv")
RESOLVED_METER_DATA.to_csv(r"C:\Users\Ratan Kumar Jha\Desktop\welcome msg\ANALYSIS OUTPUT\FINAL_DATA\WELCOME_MSG_METER_DATA_FINAL_DATA.csv")

In [42]:
RESOLVED_METER_DATA.head(3)

,WO Status,Consumer ID,installation_number,New Meter No,S2S Meter,MDM_Status,Never,Meter Replacement,Aging_Creation_Date,Remarks,Detailed_Remarks,Utility Name,Replacement Date,Aging,Bucket,Bucket1,Category Name,Type,Phase,Section_Name,Division_Name,Status,Aging_Creation_Date_BACKDATE,Year-Week,Month,Agging_bucket_30,Resolved Cases,Count,Week,NEW_METER_COUNT,RESOLVED_METER_COUNT
0,edf_mi_verification_approved,101032204,5001980022,LT8058742,NaN,Installed,NaN,SUCCESS,2024-01-02,Welcome Msg Not Sent,"Communicating not ""Y"" in MDM",SBPD,2023-12-29,4,04 - 07,04 - 07,DS-IID,Prepaid,3.0,Sec-Rajapur,Pataliputra,Closed,2023-12-25,2024-00,1,<=30,0,1,1,1,1
1,edf_mi_verification_approved,101292593,5002100094,LT8069536,NaN,Installed,NaN,SUCCESS,2024-01-02,Welcome Msg Not Sent,"Communicating not ""Y"" in MDM",SBPD,2023-12-28,5,04 - 07,04 - 07,DS-IID,Prepaid,3.0,Sec-Buddha Colony,New Capital,Closed,2023-12-23,2024-00,1,<=30,0,1,1,1,1
2,edf_mi_verification_approved,101726012,5002764589,LT8069508,NaN,Installed,NaN,SUCCESS,2024-01-02,Welcome Msg Not Sent,"Communicating not ""Y"" in MDM",SBPD,2023-12-28,5,04 - 07,04 - 07,DS-IID,Prepaid,3.0,Sec-Buddha Colony,New Capital,Closed,2023-12-23,2024-00,1,<=30,0,1,1,1,1

In [43]:
#NB_SB_COMBINED_DATAFRAME.drop_duplicates(subset=['MFG_SERIAL_NUM','UDC_ID',"DECODE(D.ORG_ID,52,'SBPDCL',102,'NBPDCL')"], keep='first', inplace=True, ignore_index=True)
#NB_SB_COMBINED_DATAFRAME[NB_SB_COMBINED_DATAFRAME.duplicated(subset=['MFG_SERIAL_NUM'], keep=False)].sort_values(by=['MFG_SERIAL_NUM'],ascending=True)

# code for getting last record of every meter

In [44]:
import pandas as pd
#pd.set_option('display.max_rows', None)



welcome_message_data = pd.read_csv(r"C:\Users\Ratan Kumar Jha\Desktop\welcome msg\ANALYSIS OUTPUT\FINAL_DATA\FINAL_DATA_ALL_MERGE_MISSING_DAYS_COUNT.csv")
welcome_message_data.drop(['Unnamed: 0'],axis=1, inplace=True)
pd.set_option('display.max_columns', None)

In [45]:
welcome_message_data.drop(['Consumer ID',
        'Meter Replacement',
        'Utility Name', 'Replacement Date', 
        'Bucket',
       'Bucket1', 'Category Name', 
       'Aging_Creation_Date_BACKDATE', 'Year-Week', 'Week',
       'Month','Agging_bucket_30','Resolved Cases','Count','lead_status','lead_date','Aging'],axis=1, inplace=True)


# this will sort the meter and aging_Creation_date
welcome_message_data = welcome_message_data.sort_values(['New Meter No', 'Aging_Creation_Date'], ascending=[True, True])

In [46]:
# after partition or group by we did lead of detailed remark

welcome_message_data['lead_Detailed_remark'] = welcome_message_data.groupby('New Meter No')['Detailed_Remarks'].shift(-1)

In [47]:
import pandas as pd

output_list = []

for meter, group in welcome_message_data.groupby('New Meter No'):
    sum_meter_aging = 0  

    for i in range(len(group)):
        starting_remark = group['Detailed_Remarks'].iloc[i]
        lead_remark = group['lead_Detailed_remark'].iloc[i]
        meter_aging_value = group['meter_aging'].iloc[i]

        if starting_remark != lead_remark:
            sum_meter_aging += meter_aging_value  
            date = group['Aging_Creation_Date'].iloc[i]  
            output_list.append({
                'meter_no': meter,
                'date': date,
                'Detailed_Remark': starting_remark,
                'Sum_meter_aging': sum_meter_aging
            })
        
            sum_meter_aging = 0
        else:
          
            sum_meter_aging += meter_aging_value  
           

# Convert to DataFrame
Dataframe_meter_compiled_category = pd.DataFrame(output_list)

# Print the DataFrame
#print(output_df)
Dataframe_meter_compiled_category.to_csv(r"C:\Users\Ratan Kumar Jha\Desktop\welcome msg\ANALYSIS OUTPUT\FINAL_DATA\Dataframe_meter_compiled_category.csv")

In [48]:
Dataframe_meter_compiled_category.to_csv(r"C:\Users\Ratan Kumar Jha\Desktop\welcome msg\ANALYSIS OUTPUT\FINAL_DATA\Dataframe_meter_compiled_category.csv")

In [49]:
import pandas as pd


Meter_compiled_Category_last_row = Dataframe_meter_compiled_category.groupby('meter_no').last().reset_index()

Meter_compiled_Category_last_row.to_csv(r"C:\Users\Ratan Kumar Jha\Desktop\welcome msg\ANALYSIS OUTPUT\FINAL_DATA\Meter_compiled_Category_last_row.csv")